// Dados de exemplo usados no MODO DEMO (sem credenciais reais).
// Cobrem as três plataformas, directs e comentários, e várias categorias
// e idiomas — para que o painel seja demonstrável imediatamente online.

export const demoMessages = [
  {
    platform: 'instagram',
    type: 'direct',
    sender_name: 'Marina Alves',
    sender_id: 'ig_1001',
    message_text: 'Oi! Adorei o conteúdo de vocês, quero muito me inscrever no próximo curso. Como faço? Meu email é marina.alves@gmail.com',
    timestamp: '2026-07-27T09:12:00Z',
    post_url: null,
  },
  {
    platform: 'instagram',
    type: 'comment',
    sender_name: 'Pedro Santos',
    sender_id: 'ig_1002',
    message_text: 'Quanto custa a mentoria? Tem parcelamento?',
    timestamp: '2026-07-27T09:40:00Z',
    post_url: 'https://instagram.com/p/Cxyz123',
  },
  {
    platform: 'facebook',
    type: 'direct',
    sender_name: 'Sofia Martín',
    sender_id: 'fb_2001',
    message_text: 'Hola, me encantaría saber más información sobre el programa. ¿Cómo puedo apuntarme?',
    timestamp: '2026-07-27T08:05:00Z',
    post_url: null,
  },
  {
    platform: 'facebook',
    type: 'comment',
    sender_name: 'James Carter',
    sender_id: 'fb_2002',
    message_text: 'This masterclass changed everything for me. Thank you so much, best decision ever!',
    timestamp: '2026-07-27T07:30:00Z',
    post_url: 'https://facebook.com/erincollege/posts/998877',
  },
  {
    platform: 'facebook',
    type: 'direct',
    sender_name: 'Ana Ribeiro',
    sender_id: 'fb_2003',
    message_text: 'Comprei o acesso mas até agora não recebi nada, isso é um absurdo. Quero um reembolso.',
    timestamp: '2026-07-27T06:50:00Z',
    post_url: null,
  },
  {
    platform: 'tiktok',
    type: 'comment',
    sender_name: 'lucas.fit',
    sender_id: 'tt_3001',
    message_text: 'Bonjour ! Combien coûte la formation ?',
    timestamp: '2026-07-27T10:15:00Z',
    post_url: 'https://tiktok.com/@erincollege/video/7333',
  },
  {
    platform: 'tiktok',
    type: 'direct',
    sender_name: 'giulia_dm',
    sender_id: 'tt_3002',
    message_text: 'Ciao! Vorrei ricevere maggiori informazioni sui vostri corsi, come funziona?',
    timestamp: '2026-07-27T10:42:00Z',
    post_url: null,
  },
  {
    platform: 'instagram',
    type: 'direct',
    sender_name: 'Crypto Deals',
    sender_id: 'ig_1099',
    message_text: 'Follow back and check my profile to earn money with crypto! bit.ly/xyz',
    timestamp: '2026-07-27T11:00:00Z',
    post_url: null,
  },
  {
    platform: 'instagram',
    type: 'comment',
    sender_name: 'Camila Duarte',
    sender_id: 'ig_1003',
    message_text: 'Vocês têm certificado no final do curso? E o material fica disponível depois?',
    timestamp: '2026-07-27T11:20:00Z',
    post_url: 'https://instagram.com/p/Cabc789',
  },
];
